import db from "../prisma/client.js";
export const findMany = (where = {}, include = {}) => db.leaveRequest.findMany({ where, include });
export const findUnique = (leaveId, include = {}) => db.leaveRequest.findUnique({ where: { leaveId }, include });
export const create = (data) => db.leaveRequest.create({ data });
export const update = (leaveId, data) => db.leaveRequest.update({ where: { leaveId }, data });
export const remove = (leaveId) => db.leaveRequest.delete({ where: { leaveId } });
export const createStudingTime = (data) => db.leaveRequestStudingTime.createMany({ data });
export const findStudingTime = (where, include = {}) => db.leaveRequestStudingTime.findUnique({ where, include });
export const updateStudingTime = (id, data) => db.leaveRequestStudingTime.update({ where: { leaveRequestStudingTimeId: id }, data });
export const deleteStudingTimes = (where) => db.leaveRequestStudingTime.deleteMany({ where });
export const findSubjects = (where, select = {}) => db.subject.findMany({ where, select });
export const findTerms = () => db.academicTerms.findMany();
export const findClassroomMember = (where, include = {}) => db.classroomMember.findFirst({ where, include });
export const findTimetables = (where) => db.timetable.findMany({ where });
export const findStudingTimeMany = (where, include = {}) => db.studingTime.findMany({ where, include });
export const findStudingTimeUnique = (studyTimeId) => db.studingTime.findUnique({ where: { studyTimeId } });
export const findStudent = (stdId) => db.student.findUnique({ where: { stdId } });
export const updateStudent = (stdId, data) => db.student.update({ where: { stdId }, data });
export const findStudentParents = (stdId) => db.studentParent.findMany({ where: { stdId }, include: { parent: true } });
export const findLeaveRequestTypes = (include = {}) => db.leaveRequestType.findMany({ include });
export const findAttendance = (where) => db.attendance.findFirst({ where });
export const createAttendance = (data) => db.attendance.create({ data });
export const updateAttendance = (attId, data) => db.attendance.update({ where: { attId }, data });
export const findAttendanceMethod = (where) => db.attendanceMethod.findFirst({ where });
export const createBehaviourTransaction = (data) => db.behaviourScoreTransaction.create({ data });
export const updateClassroomMembers = (where, data) => db.classroomMember.updateMany({ where, data });
